
version: 2

models:
  - name: model_project_dep
    description: "Model that has dependecy on another project"
    columns:
      - name: id
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
