
version: 2

models:
  - name: copy1
    description: "Copy 1"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: copy2
    description: "Copy 2"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
